Added int to days TimeInterval helper.
bakkenbaeck/SweetSwift pull request #28
Opened 2018-04-09 14:49 UTC by Elland

Should simplify dealing with time boundary checks such as "is this older than X days".

```swift
if data.creationDate.timeIntervalSinceNow >= 8.days { return "Is more than a week old" }
```

2018-04-10 09:14 UTC, designatednerd commented on Sources/Int+Date.swift
>      /// Ex: 3.days == 259200 seconds. Of courrse is not Date/Time aware. Use it with care.
Nit: `courrse` -> `course`

2018-04-10 09:23 UTC, designatednerd requested changes
So my objection to this is more from a standpoint of "I know we say this is only for approximate math but we should really be encouraging consumers of this library to use exact date math, not time intervals."

What about an extension on NSDate that allows you to get the NSDateComponents between two dates? I'm  basically thinking something like `dateComponentsSince:` and `dateComponentsSinceNow`, which returns the `NSDateComponents` between two dates. 

You might have to pass in a default calendar in the function so people can do math on whatever calendar they want, but for the most part that should be `current` anyway. 

The other advantage of this is that then you can check any unit of the components (`day`, `month`, `year`) without having to write additional extension methods for them.

2018-04-10 12:52 UTC, 3lvis commented
Isn't doing something like this better?

![screen shot 2018-04-10 at 14 52 04](https://user-images.githubusercontent.com/1088217/38557889-c4289ec0-3cce-11e8-8a3e-4488e0a7bc82.png)

2018-04-10 14:56 UTC, designatednerd commented
@3lvis The third bullet point on that slide indicates it's not for use for comparing dates

2018-04-10 14:57 UTC, designatednerd commented
(meaning, you can say "is date x within the unit granularity of seconds / minutes / hours of date y", but it doesn't tell you how far date x is from date y, which i think is what @Elland is trying to calculate here)

2018-04-10 21:44 UTC, 3lvis commented
I see, thanks for clarifying :)

2018-04-23 09:33 UTC, closed without merging

2018-04-23 09:33 UTC, Elland commented
Gonna use `Calendar` and `DateInterval` instead.